### ISSUE TITLE
What tests are needed by 1.0.0 MVP?

### ISSUE THREAD

**Issue by chrisvogt** [chrisvogt/gatsby-theme-private-sphere#7]
As of writing this issue, this theme is completely untested 😬. This issue should determine what tests this project will include by the 1.0.0 MVP milestone.

### Tasks

- [ ] Determine and define what type of tests should be included for the release 1.0.0 (_i.e._, unit, integration, smoke, UI).
- [ ] Based on the above decision, determine if there is a testing framework that would be appropriate to use.
- [ ] Based on the above, write issues and add them to the project.
